# config/meta.yml

meta_product_name: "CinéSelect"
meta_title: "CinéSelect – Vos critères, notre sélections !"
meta_description: "Une selection de films ou series selon vos critères"
meta_image: "meta_image.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account" # required for Twitter Cards
